version: 1

url: https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyN7P4D2UeFpMrkrxKuoWldpUNDRBWDJEWEJIQ1JTS0RMSURYNElBQ1RIRyQlQCN0PWcu
#url: https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyGJLZRGxFtNOn7Mf0Ca3QRJUMlFRMU1OU1U0VEFJUk0zNFNDTE9UWUhNVC4u
answers:
  - generator: constant
    options:
      value: 'No'
