version: 1

#url: https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyGJLZRGxFtNOn7Mf0Ca3QRJUMlFRMU1OU1U0VEFJUk0zNFNDTE9UWUhNVC4u
#url: https://forms.office.com/Pages/ResponsePage.aspx?id=XYP-cpVeEkWK4KezivJfyGJLZRGxFtNOn7Mf0Ca3QRJUOTZQMDBQVVIzSUo5VlRHQ0lVSU43UkwwUS4u

answers:
  - generator: constant
    options:
      value: 'No'
